### ISSUE TITLE
Use the library inside a jsx/tsx component

### ISSUE THREAD

**Issue by Feka7** [WebLogin/trendchart-elements#1]
Hi, I would like to ask if is possible in some way to use your library inside a JSX/TSX component. I'm trying to use it in my code but I encountered an error.

To reproduce

1. install the package
`npm install @weblogin/trendchart-elements`

2. import a chart
`import { TcLine } from "@weblogin/trendchart-elements";`

3. create a component
```
import { TcColumn } from "@weblogin/trendchart-elements"

export default function Page() {
  return (
    <main>
      <div>
       <TcColumn />
      </div>
    </main>
  )
} 
```

The error encountered is the following:
> 'TcColumn' cannot be used as a JSX component.
>   Its type 'typeof TcColumn' is not a valid JSX element type.
>     Types of construct signatures are incompatible.
>       Type 'new () => TcColumn' is not assignable to type 'new (props: any, deprecatedLegacyContext?: any) => Component<any, any, any>'.
>         Type 'TcColumn' is missing the following properties from type 'Component<any, any, any>': context, setState, forceUpdate, props, and 2 more.

**Comment by Mushr0000m** [comment]
Hi ! Sorry I've never used JSX or TSX, so I downloaded a helloword project and tested it. I think you just have to change your code to use the TrendChart Elements like any other HTML tag. Here is an example with some values : 

```TS
import '@weblogin/trendchart-elements';

export default function Page() {
  return (
    <main>
      <div>
       <tc-column values="[11,7,6,8,10,12,8,10,2]"></tc-column>
      </div>
    </main>
  )
} 
```

Tell me if it help or if missunderstood your issue

**Comment by Feka7** [comment]
Hi @Mushr0000m, thanks for the help! The code you share triggers a typo in TSX files, The walkaround I've found for the moment is to use the following code at the beginning:
```
declare global {
    namespace JSX {
      interface IntrinsicElements {
        'tc-column': any;
      }
    }
  }
```
I think could be cool if in the future the package will support also Typescript :)

**Comment by Mushr0000m** [comment]
Weird I've coded it in Typescript : https://github.com/WebLogin/trendchart-elements/tree/master/src and the dist folder contains all the declaration files https://www.npmjs.com/package/@weblogin/trendchart-elements?activeTab=code

I think it's more relative to being compatible with React itself.

**Comment by Feka7** [comment]
Yeah you are right I meant to say React
