### ISSUE TITLE
Failed to resolve module specifier "tslib"

### ISSUE THREAD

**Issue by lucky4udanny** [WebLogin/trendchart-elements#7]
When switching from trendchart-elements@1.1.0 to trendchart-elements@2.0.1 in my vue3 vite project, console shows:

`Uncaught TypeError: Failed to resolve module specifier "tslib". Relative references must start with either "/", "./", or "../".`

I have tslib installed.
```
$ npm ls tslib
[project]
└── tslib@2.6.3
```
I have verified that tslib is functional in my project. The error only occurs when switching trendchart versions:
```
                // const url = "https://cdn.jsdelivr.net/npm/@weblogin/trendchart-elements@1.1.0/dist/index.js/+esm";
                const url = "https://cdn.jsdelivr.net/npm/@weblogin/trendchart-elements@2.0.1/dist/index.js";
```

**Comment by Mushr0000m** [comment]
Hi, can you provide more code so i can reproduce the error ?

Also I notice there is a difference between your lines here : 
```
// const url = "https://cdn.jsdelivr.net/npm/@weblogin/trendchart-elements@1.1.0/dist/index.js/+esm";
const url = "https://cdn.jsdelivr.net/npm/@weblogin/trendchart-elements@2.0.1/dist/index.js";
```
The second line (for v2) doesn't end with `/+esm` like the first one, can the error be from here ?

**Comment by lucky4udanny** [comment]
I'm new to Vue3 and discovering the difference between ECMAScript Module (ESM) and CommonJS. Missing "/+esm" on the end of the 2.0.1 url was the issue. Newby.
Thank you.
